
filebeat.inputs:
- type: log
  paths:
  - /log/*.log


setup.template.name: "api"
setup.template.pattern: "api"
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["192.168.1.102:9200"]
  index: "api"
  #  index: "app-%{[agent.version]}-%{+yyyy.MM.dd}"
#  template.name: "filebeat"
#  template.pattern: "*"
#  template.path: "filebeat.template.json"
  template.overwrite: true
  username: "elastic"
  password: "changeme"


