version: '2'

services:

  app:
    container_name: web-api
    ports:
      - "9090:80"
    image: yonh/php:alpine-apache
    restart: always
    volumes:
      - .:/app
    environment:
      - WEBAPP_ROOT=public

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.0
    volumes:
    - ./conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
    - ./log:/log
