
filebeat.inputs:
- type: log
  paths:
  - /log/*.log


setup.template.name: "app"
setup.template.pattern: "app"
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["123.57.11.119:9200"]
  # index: "app"
  index: "app-%{[agent.version]}-%{+yyyy.MM.dd}"
#  template.name: "filebeat"
#  template.pattern: "*"
#  template.path: "filebeat.template.json"
  template.overwrite: true
  username: "elastic"
  password: "haoyida123"

